### PR TITLE
[3.x] Scons boilerplate for building projects. Android, iOS builds.

### PR DESCRIPTION
**Pull request by Faless**
`3.x` version of #636

### CODE REVIEW

**Comment by Faless** [comment]
Might still need a small fix for iOS simulator

**Comment by Faless** [comment]
> Might still need a small fix for iOS simulator

No, 3.x version was okay.

**Review by Calinou — APPROVED** [review]
Code looks good to me (although I haven't tested it locally and don't have much experience working with GDNative).

**Comment by akien-mga** [comment]
Would be good if @BastiaanOlij @m4gr3d could test this against their GDNative plugins, to make sure that it's not too major a disruption for `3.x` users.

If we can make it so that it still supports the "old" style of building projects with their own full blown SCons file (i.e. the syntax to build the library only doesn't change), then I think it should be fine for 3.5.

**Review by akien-mga — APPROVED** [review]
Looks good to me.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
