### PR TITLE
Fix vararg methods forwarded to the `ClassDB` singleton

### PR DESCRIPTION
**Pull request by dsnopek**
Aims to fix the CI issues with Godot PR https://github.com/godotengine/godot/pull/91392 as well as allowing forwarded vararg methods to work.

This will need to be cherry-picked to the `4.2` branch before CI on that PR can pass.

### CODE REVIEW

**Comment by dsnopek** [comment]
PR https://github.com/godotengine/godot-cpp/pull/1486 should fix the test failure - it's unrelated to the changes here

**Comment by AThousandShips** [comment]
My bad accidentally made my own fic for this, will make that just an improvement and leave this for the immediate fix

**Review by AThousandShips — APPROVED** [review]

**Comment by dsnopek** [comment]
Thanks for the review!

**Comment by dsnopek** [comment]
Cherry-picked for 4.1 in PR https://github.com/godotengine/godot-cpp/pull/1491

**Comment by dsnopek** [comment]
Cherry-picked for 4.2 in PR https://github.com/godotengine/godot-cpp/pull/1492

**Pull request merged**
