### PR TITLE
Add visibility-hidden to CMake build

### PR DESCRIPTION
**Pull request by APokorny**
This should make all symbols that are not marked otherwise have hidden visibility. There still may be exposed symbols if marked with respective attributes.

### CODE REVIEW

**Comment by APokorny** [comment]
This is to avoid symbol clashes when multiple versions of godot-cpp are loaded through different plugins.
Scons seems to do something similar already,

**Comment by dsnopek** [comment]
Thanks!

With scons, visibility hidden is the default, but there is an option to change it. Would it be possible to add an option for cmake as well?

**Comment by APokorny** [comment]
You can change the behavior later - even in downstream projects via set_target_properties(<targets...> PROPERTIES CXX_VISIBILITY_PRESET  default )

**Comment by enetheru** [comment]
I think this should be merged. Even though we're aiming for feature _and interface_ parity, even without the option displayed it still adds something missing from the cmake build that is in the scons one. Perfect is the enemy of the good and all. it's trivial to add a cache entry which will show up in 'cmake -LH'

**Comment by dsnopek** [comment]
Ok, let's merge this and then add an option in a follow-up

**Review by dsnopek — APPROVED** [review]

**Comment by dsnopek** [comment]
Cherry-picked for 4.2 in PR https://github.com/godotengine/godot-cpp/pull/1631

**Comment by dsnopek** [comment]
Cherry-picked for 4.3 in PR https://github.com/godotengine/godot-cpp/pull/1632

**Pull request merged**
