### PR TITLE
Search correct python interpeter in case missing default "python"

### LINKED ISSUE #491: CMake project broken on systems without "python" interpreter
I use Devuan Testing without `python2` so I don't have `python` interpreter only `python3`.

I suppose it should use `find_package(PythonInterp)` to detect correct python interpreter and call `${PYTHON_EXECUTABLE}`

### PR DESCRIPTION
**Pull request by o01eg**
Fixes  #491

### CODE REVIEW

**Comment by o01eg** [comment]
Are there any news about accepting cmake-related fixes?

**Comment by Calinou** [comment]
@o01eg The CMake build system isn't tested on CI, and there are only a few people using it. You need to ask one of the people in https://github.com/godotengine/godot-cpp/issues/509 to review it :slightly_smiling_face:

**Comment by vnen** [comment]
This now needs a rebase to fix conflicts.

**Comment by o01eg** [comment]
Rebased.

**Comment by vnen** [comment]
Thanks!

**Pull request merged**
