### PR TITLE
Cherry-picks for the godot-cpp 4.2 branch - 1st batch

### PR DESCRIPTION
**Pull request by dsnopek**
The 1st batch of PR's marked with `cherrypick:4.2`

### CODE REVIEW

**Comment by AThousandShips** [comment]
See discussion on:
* https://github.com/godotengine/godot-cpp/pull/1357

I'd hold off cherry picking this, if at all (also for 4.1)

**Comment by dsnopek** [comment]
> I'd hold off cherry picking this, if at all (also for 4.1)

We can hold off while figuring out the issue with `SAFE_NUMERIC_TYPE_PUN_GUARANTEES(uint64_t)`, however, I'd really like to cherry-pick this eventually. Without this change, GDExtensions compiled with the 4.1 or 4.2 versions of godot-cpp will be subtly incompatible with Godot 4.3+ if they get a packed array or string with enough elements. And developers may chose to build their extension with the 4.1 or 4.2 version of godot-cpp to make it compatible with more versions of Godot.

**Comment by AThousandShips** [comment]
I'd suggest just removing it from this and not hold this batch back, will do some further looking into that bug but been having problems testing 32 bit builds, but will look back into it

**Comment by dsnopek** [comment]
Ok, I've removed the cherry-pick of PR https://github.com/godotengine/godot-cpp/pull/1357 for now

**Pull request merged**
