### PR TITLE
Use enum type in GDExtension info structs for better readability

### PR DESCRIPTION
**Pull request by touilleMan**
This is related the fix for once https://github.com/godotengine/godot/pull/67138 is merged

### CODE REVIEW

**Comment by akien-mga** [comment]
I think you need to update the Godot header too for this to pass CI, no?

**Comment by akien-mga** [comment]
Some more:
```
src\core\class_db.cpp(98): warning C4838: conversion from 'GDNativeVariantType' to 'uint32_t' requires a narrowing conversion
src\core\class_db.cpp(244): error C2397: conversion from 'GDNativeVariantType' to 'uint32_t' requires a narrowing conversion
```

**Comment by akien-mga** [comment]
Seems like you use the message of a fixup commit as the message for the squashed commit.

**Comment by touilleMan** [comment]
> Seems like you use the message of a fixup commit as the message for the squashed commit.

@akien-mga not sure what you mean... I've changed the commit message in case it was not understandable enough ;-)

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
