### PR TITLE
[Web] Don't cache emsdk

### PR DESCRIPTION
**Pull request by AThousandShips**
See:
* https://github.com/godotengine/godot/pull/98965

### CODE REVIEW

**Review by dsnopek — APPROVED** [review]
Thanks! Seems to match what was done in the Godot repo :-)

**Comment by AThousandShips** [comment]
Thank *you*!

**Comment by dsnopek** [comment]
Cherry-picked for 4.2 in PR https://github.com/godotengine/godot-cpp/pull/1694

**Comment by dsnopek** [comment]
Cherry-picked for 4.3 in PR https://github.com/godotengine/godot-cpp/pull/1695

**Pull request merged**
