### PR TITLE
Fix binding generation command in CMake to escape path strings if necessary

### PR DESCRIPTION
**Pull request by PierceLBrooks**
These changes resolve the issue that I filed here: https://github.com/godotengine/godot-cpp/issues/865

### CODE REVIEW

**Comment by Calinou** [comment]
Is the change no longer required?

**Comment by PierceLBrooks** [comment]
> Is the change no longer required?

My mistake, as I was closing out some other obsolete pull requests of mine this was overzealously included. I will reopen it now. Most cases will nonetheless work fine without the double quotes around the path parameter, but I still cannot guarantee success on all platforms where the corresponding string value contains space characters.

**Comment by PierceLBrooks** [comment]
I have resolved the merge conflict which emerged recently.

**Comment by enetheru** [comment]
I believe with recent changes this PR is no longer needed.

**Comment by enetheru** [comment]
I cannot replicate the error, I've tried all combinations of path separators, windows, and msys environments. I'm considering this solved.

**Comment by dsnopek** [comment]
Closing per @enetheru's testing

**Pull request closed without merging**
