### PR TITLE
Import `env` if possible

### PR DESCRIPTION
**Pull request by adamscott**
This PR make it possible to import `env` and use it instead of creating one from scratch every time. 

Handy because we encourage users to use the godot-cpp SConstruct file as a base to their projects (see the test project). So, if a project want to override specific settings, (eg. make a path local to their SConstruct file, not local to the godot-cpp/SConstruct file), it can do so.

### CODE REVIEW

**Comment by adamscott** [comment]
For unknown reasons, if I run `./misc/scripts/file_format.sh`, it changes a lot more than my changes.

**Comment by Faless** [comment]
> For unknown reasons, if I run `./misc/scripts/file_format.sh`, it changes a lot more than my changes.

Make sure you have the same version of `black` used by CI (currently `22.3.0`):
```
pip3 install black==22.3.0
```

**Comment by adamscott** [comment]
@Faless It worked! Thanks!

**Review by Faless — CHANGES_REQUESTED** [review]
Looking good, just some nit picks to make the behavior clearer (I think?):

```diff
diff --git a/SConstruct b/SConstruct
index 0edf7fa..11ec4cf 100644
--- a/SConstruct
+++ b/SConstruct
@@ -4,19 +4,11 @@ import os
 import platform
 import sys
 import subprocess
-from typing import TYPE_CHECKING
 from binding_generator import scons_generate_bindings, scons_emit_files
-from SCons.Script import Environment
 from SCons.Errors import UserError
-from SCons.Variables import BoolVariable, EnumVariable, PathVariable
 
 EnsureSConsVersion(4, 0)
 
-try:
-    Import("env")
-except:
-    pass
-
 
 def add_sources(sources, dir, extension):
     for f in os.listdir(dir):
@@ -59,10 +51,13 @@ elif ARGUMENTS.get("platform", ""):
 else:
     raise ValueError("Could not detect platform automatically, please specify with platform=<platform>")
 
-# Default tools with no platform defaults to gnu toolchain.
-# We apply platform specific toolchains via our custom tools.
-if not "env" in globals() or TYPE_CHECKING:
+try:
+    Import("env")
+except:
+    # Default tools with no platform defaults to gnu toolchain.
+    # We apply platform specific toolchains via our custom tools.
     env = Environment(tools=["default"], PLATFORM="")
+
 env.PrependENVPath("PATH", os.getenv("PATH"))
 
 # Default num_jobs to local cpu count if not user specified.
```

**Review by dsnopek — APPROVED** [review]
This looks great to me! And Fabio's requested changes have been made

**Comment by dsnopek** [comment]
Discussed at the GDExtension meeting, and we think this makes sense.

**Comment by dsnopek** [comment]
Thanks!

**Pull request merged**
