### PR TITLE
Add OSX arm64 build target.

### PR DESCRIPTION
**Pull request by Faless**
New "macos_arch" to specify the desired arch, and "macos_sdk_path" to override the default SDK path.

### CODE REVIEW

**Comment by DrMoriarty** [comment]
@Faless Hi! What about universal architecture? like this https://github.com/godotengine/godot-cpp/pull/529/files

**Comment by samsface** [comment]
@Faless This is cool. How would I deploy an arm build though seeing gdnlib only offers x32 & x64 alts for Mac OSX?

**Comment by Calinou** [comment]
> @Faless This is cool. How would I deploy an arm build though seeing gdnlib only offers x32 & x64 alts for Mac OSX?

This is being tracked in https://github.com/godotengine/godot/issues/48959.

**Comment by samsface** [comment]
Ok cool this worked. I was able to create a fat binary pretty easy using the CMake build: https://github.com/samsface/godot-steam-api/blob/a62734b45f0630a005891df48b10815e170e90c8/lib/godot-cpp/conanfile.py

Though then found out steam's sdk won't ever link with arm so was all for nothing in the end :sweat_smile: .

**Pull request merged**
