### PR TITLE
Cherry-picks for the godot-cpp 4.1 branch - 6th batch

### PR DESCRIPTION
**Pull request by dsnopek**
The 6th batch of PR's marked with `cherrypick:4.1`

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by AThousandShips** [comment]
Would need to resolve https://github.com/godotengine/godot-cpp/issues/1296 before merging this

**Comment by akien-mga** [comment]
> Would need to resolve #1296 before merging this

No, this is what's needed to resolve #1296.

But I didn't merge yet due to CI being broken by https://github.com/godotengine/godot/issues/84735.

**Comment by akien-mga** [comment]
> But I didn't merge yet due to CI being broken by [godotengine/godot#84735](https://github.com/godotengine/godot/issues/84735).

I worked it around with #1308 and cherry-picked that to `4.1`. So this should be ready to merge after rebasing to pass CI.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
