### PR TITLE
Update Getting Started section of README.md

### PR DESCRIPTION
**Pull request by dgcole**
Not sure if there is any procedure for PRs on this repo / template that I am missing, hopefully not.

When updating, I noticed that the implementation of the demo extension was changed with #1095 , but the corresponding README.md sections were not updated, so I figured I might as well make a PR.

### CODE REVIEW

**Review by dsnopek — APPROVED** [review]
Ah, thanks for catching that! This looks good to me :-)

**Review by paddy-exe — APPROVED** [review]
Looks good to me as well! Nice catch!

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
This should update the note at the top of the README to say that `master` is 4.1+ and to include `4.0` in the branches mentioned people may want to check out. Otherwise looks good to me.

**Comment by dgcole** [comment]
> This should update the note at the top of the README to say that `master` is 4.1+ and to include `4.0` in the branches mentioned people may want to check out. Otherwise looks good to me.

Good call, I've updated the warning to clarify that the current version on `master` is for 4.1+, and I added a note to switch to `4.0` for `4.0.x` versions of the engine.

**Comment by paddy-exe** [comment]
@dgcole  This needs a squash to be merged.

**Comment by dsnopek** [comment]
This document is helpful for squashing your commits into a single one:

https://docs.godotengine.org/en/stable/contributing/workflow/pr_workflow.html#the-interactive-rebase

There also appears to be a "coding standards" failure in CI: https://github.com/godotengine/godot-cpp/actions/runs/5060252047/jobs/9087748389?pr=1115

It looks like a trailing space at the end of this line:

```
> This repository's `master` branch is only usable with the latest version of 
```

**Comment by dsnopek** [comment]
Thanks!

**Pull request merged**
