### PR TITLE
Add missing Vector3::operator Vector3i definition

### PR DESCRIPTION
**Pull request by zhehangd**
The definition is simply missing.

### CODE REVIEW

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
The matching `Vector2i` operator seems to be missing in `vector2.cpp` too, could you add that too?

**Comment by zhehangd** [comment]
Done. Btw I notice there is no veci to vec conversion, is that intentional?

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
> Btw I notice there is no veci to vec conversion, is that intentional?

This could be added, though I see it also needs to be added in godotengine/godot for Vector3i.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
> > Btw I notice there is no veci to vec conversion, is that intentional?
> 
> This could be added, though I see it also needs to be added in godotengine/godot for Vector3i.

Done in #707.

**Pull request merged**
