### PR TITLE
Don't use Ref<T> in Object.hpp

### PR DESCRIPTION
**Pull request by Zylann**
Fixes https://github.com/godotengine/godot-cpp/issues/432

### CODE REVIEW

**Comment by m4gr3d** [comment]
@BastiaanOlij Any luck this could get merged in quickly. As of now, generating the library is broken.

**Comment by BastiaanOlij** [comment]
@m4gr3d if you can confirm this works as advertised I'm happy for it to be merged

**Comment by m4gr3d** [comment]
@BastiaanOlij It does. I've actually included the changes into my [PR](https://github.com/godotengine/godot-cpp/pull/436) for that reason. Once this is merged, I'll rebase accordingly.

**Comment by BastiaanOlij** [comment]
Then I'm all for merging and so it is merged. We'll see if there is any feedback from people running into issues but it sounds like a solid change.

**Pull request merged**
