### PR TITLE
[SCons] Add "optimize" and "debug_symbols" options.

### PR DESCRIPTION
**Pull request by Faless**
`optimize = auto|none|debug|speed|size|0|1|2|3`
`debug_symbol = True|False`

optimize == "auto" will produce:
- "debug" for `target="debug"` builds
- "speed" for `target="release"` builds
- ~Add a release_debug target.~ Dropped, should be moved to a separate PR after discussion on: https://github.com/godotengine/godot-proposals/issues/3371

~Depends on: #836~ Merged

### CODE REVIEW

**Comment by jordo** [comment]
> * Add a release_debug target.
>       People seem confused by the fact that it's missing, no matter how much we explain that it's just debug + optimize.

When I first started using godot, I was completely confused by how the godot build system uses 'debug' and 'release'.  It's confusing to native & c++ developers because 'debug' and 'release' build profiles in other build systems usually translate directly to compiler switches of the compiler optimization levels & debug flags.

In godot, 'debug' and 'release' build targets are completely decoupled from the native build profiles in (compiler opt level, and debug flags), which is I think where the confusion comes from.  So you can do a 'release' build, with -O0 and -g.  And you can do a 'debug' build, with -O3 and no debug symbols.

So the question for me has always been, what does 'debug' and 'release' even mean as a godot build target?  And that question I don't think is succinctly answered in the godot development docs, which is for me where the confusion comes from.  

To me, the 'debug' and 'release' build target's for godot build system really just end up translating to the ability to debug scripts, which adds a lot of additional internal engine overhead, but it's completely orthogonal to the native compilation step.

**Comment by Faless** [comment]
> To me, the 'debug' and 'release' build target's for godot build system really just end up translating to the ability to debug scripts

@jordo , well, that's probably another misunderstanding I guess, you probably want to quote/move that comment to this proposal which concerns godot targets: https://github.com/godotengine/godot-proposals/issues/3371 .

**Comment by jordo** [comment]
> @jordo , well, that's probably another misunderstanding I guess, you might want to quote those comments to this proposal which concerns godot targets

Wait... am I still misunderstanding that or is that correct?

**Comment by Faless** [comment]
> Wait... am I still misunderstanding that or is that correct?

Well, it's not just for "debugging scripts", but (some) engine internals too, and it is not `completely orthogonal to the native compilation step.` because it does require some specific compiler flags e.g. `-frtti`, and as explained by both scons and the linked proposal **the editor cannot even build in release** mode (only `release_debug`, or optimized debug if you wish).

**Comment by jordo** [comment]
> Well, it's not just for "debugging scripts", but (some) engine internals too, and it is not `completely orthogonal to the native compilation step.` because it does require some specific compiler flags e.g. `-frtti`, and as explained by both scons and the linked proposal **the editor cannot even build in release** mode (only `release_debug`, or optimized debug if you wish).

OK good, that's what my current understanding is.  I should have said orthogonal to the native compiler optimization level & debug level.  i.e. you can do `target='debug' optimize=3 debug_symbol=false`, and `target='release' optimize=none debug_symbol=true`

**Comment by Faless** [comment]
> you can do `target='debug' optimize=3 debug_symbol=false`

No, you can't `target=debug debug_symbol=false` with the current Godot build system, or, better, you can, but `debug_symbol=false` is ignored.

The description states: `"Add debugging symbols to release/release_debug builds"`

**Review by akien-mga — APPROVED** [review]
Looks good to me.

This goes a bit beyond what we do in upstream Godot where the `optimize` and `debug_symbols` options are tied to `target`, but I think we should refactor Godot's scripts to do what is done here.

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
