### PR TITLE
Implementing dictionary operators

### PR DESCRIPTION
**Pull request by BastiaanOlij**
Requires https://github.com/godotengine/godot/pull/55247

Implement accessing dictionary through index. The test case in our test project works but fails on returning the dictionary which is a different issue. The problem here is that `return dict` will do a swap with a temporary dictionary object. This object does not instance a Godot object and the error happens on trying to free this non-existent object. We can see in the log that the dictionary was returned correctly:
```
USER ERROR: Condition "!_p" is true.
   at: Dictionary::_unref (core\variant\dictionary.cpp:244) - Condition "!_p" is true.
test dictionary {foo:bar, hello:world}
```

CI will fail until `godot-headers` is updated.

### CODE REVIEW

**Comment by BastiaanOlij** [comment]
Currently crashes on attempting to update the variant in the dictionary.

**Comment by BastiaanOlij** [comment]
Changing over to using `operator[]` on the Godot side as @groud suggested (see https://github.com/bruvzg/godot/pull/1), modifying the dictionary now works. This actually does enough for what I need it to do :P

However, the `return dict` at the end of the test case in our test example results in:
```
USER ERROR: Condition "!_p" is true.
   at: Dictionary::_unref (core\variant\dictionary.cpp:244) - Condition "!_p" is true.
```

Looks like it unreferences the dictionary held within when the variable goes out of scope.

**Review by akien-mga — APPROVED** [review]

**Comment by akien-mga** [comment]
I guess you need to update godot-headers to latest upstream to fix the build.

**Comment by BastiaanOlij** [comment]
> I guess you need to update godot-headers to latest upstream to fix the build.

Yup, all done now

**Comment by akien-mga** [comment]
Thanks!

**Pull request merged**
