### PR TITLE
Fix #1064 and LINKFLAGS typo for "-static"

### LINKED ISSUE #1064: `Can't open dynamic library: [...] error: Error 126: The specified module could not be found.` But the .dll is right there
System: Windows 11
Godot Version:  v4.0.stable.official.92bee43ad
godot-cpp version: [4.0 branch](https://github.com/godotengine/godot-cpp/tree/4.0)
extension source code: [qrnative](https://github.com/fenix-hub/qrnative-cpp)

Last time I tried to compile and use my custom extension worked (it was on Godot 4 beta 3).
Even after updating everything, and following the documentation, when I try to use the .dll in Godot after compilation of both `godot-cpp` and my library, the following message appears in the Editor:
```console
Godot Engine v4.0.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:70 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started ---
  Can't open dynamic library: D:/Development/GodotEngine/4.x/qrnative-cpp/project/addons/qrnative/bin/windows/libqrnative.windows.template_debug.x86_64.dll, error: Error 126: The specified module could not be found.
  .
  core/extension/gdextension.cpp:400 - GDExtension dynamic library not found: D:/Development/GodotEngine/4.x/qrnative-cpp/project/addons/qrnative/bin/windows/libqrnative.windows.template_debug.x86_64.dll
  Failed loading resource: res://addons/qrnative/qrnative.gdextension. Make sure resources have been imported by opening the project in the editor at least once.
```
Altough the path to the .dll is correct and there are no typos.
image
Here's the `.gdextension` file
```
[configuration]

entry_symbol = "qrnative_init"

[libraries]

windows.debug.x86_64 = "bin/windows/libqrnative.windows.template_debug.x86_64.dll"
# also tried with "res://addons/qrnative/bin..."
```
I've put the link to the source code, if anybody using w11 want's to try to test the extension. The source code contains the example project used in this issue.

Anyway, [compilation tests](https://github.com/fenix-hub/qrnative-cpp/actions/runs/4331843708/jobs/7563941263) work on all of the desktop platforms, so I don't know if I'm really missing something or it is something on Windows 11.

### PR DESCRIPTION
**Pull request by feiyunw**
This PR closes #1064, and #976 if it happens to MinGW only.
I suggest applying PR #1059 's patch before test this one.

Statically linked DLL will not depend on external MinGW DLLs (like libgcc_s_seh-1.dll, libstdc++-6.dll and libwinpthread-1.dll), thus it can be loaded by itself.

BTW, "--static" should be "-static".

FYI:
[gcc: -static](https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/Link-Options.html#index-s)
[ld: -static](https://sourceware.org/binutils/docs/ld/Options.html#index-_002dstatic)

### CODE REVIEW

**Review by bruvzg — APPROVED** [review]
Probably it should be an option (enabled by default), similar to the Godot build configs:
```python
BoolVariable("use_static_cpp", "Link MinGW/MSVC C++ runtime libraries statically", True)
```

And also forced for MSVC build:
```python
env.AppendUnique(CCFLAGS=["/MT"])
```

I'm not sure why we are setting `-O3` for debug build, but since it's done for cross-build, it should be the same for native/msys build (or removed from both).

**Comment by bruvzg** [comment]
> I suggest applying PR https://github.com/godotengine/godot-cpp/issues/1059 's patch before test this one.

A wrong link? This issue seems to be unrelated to static linking.

**Comment by feiyunw** [comment]
> > I suggest applying PR #1059 's patch before test this one.
> 
> A wrong link? This issue seems to be unrelated to static linking.

Unrelated to this issue, but tools\my_spawn.py has a (deadlock?) bug spoiling MinGW build.

**Comment by feiyunw** [comment]
> I'm not sure why we are setting `-O3` for debug build, but since it's done for cross-build, it should be the same for native/msys build (or removed from both).

`-O3` is removed.
It is overridden and handled in tools/targets.py

**Review by Calinou — APPROVED** [review]

**Comment by dsnopek** [comment]
Discussed at the GDExtension meeting: overall, we think this makes sense, however, we think it should be an option that is enabled by default as suggested by @bruvzg in an earlier comment.

**Comment by dsnopek** [comment]
I just tested this one and it fixed the problem for me! I think the only thing that still needs to be done here is adding the option that's enabled by default. If the OP doesn't have time to do this, I may pick it up some time this week.

**Comment by akien-mga** [comment]
Superseded by #1203. Thanks for the contribution!

**Pull request closed without merging**
