### PR TITLE
Implement `callable_mp()` and `callable_mp_static()`

### LINKED ISSUE #1089: Expose callable_mp macros in godot-cpp?
Engine has a macros `callable_mp` which uses class **CallableCustomMethodPointerRetC** that allow to assign native method. But I cant find analogue in GDExtension.

Godot 4.0

### PR DESCRIPTION
**Pull request by dsnopek**
This is the godot-cpp counterpart to PR https://github.com/godotengine/godot/pull/79005 (which this PR depends on).

It very minimally works! It adds a single test case that passes :-)

~~However, it's a draft because:~~

~~1. I want to add more test cases to ensure it works with void functions and const methods that return a value~~
~~2. I haven't added `callable_mp_static()` yet~~

This is now ready for review and has full test coverage!

Unfortunately, the tests will fail on GitHub CI until the Godot PR is merged.

Fixes #1089

### CODE REVIEW

**Comment by dsnopek** [comment]
`callable_mp_static()` is implemented in my latest push, and there's now full test coverage. So, this is ready for review!

Unfortunately, the tests will fail on GitHub CI until the Godot PR is merged.

**Comment by rburing** [comment]
This looks great! This will remove the need for a (registered) dummy "factory" class/method to register a physics server from a GDExtension, and allow using a static callback instead, [as it's done in core](https://github.com/godotengine/godot/blob/46424488edc341b65467ee7fd3ac423e4d49ad34/servers/register_server_types.cpp#L281).

cc @mihe for Godot-Jolt.

**Comment by ozzr** [comment]
I have been waiting for this. 
The engine has way too many useful macros that should be exposed to GDExtension

**Comment by dsnopek** [comment]
I just updated this to work with @maiself's alternative PR https://github.com/godotengine/godot/pull/79005

**Comment by akien-mga** [comment]
The upstream PR was merged, so this can be revisited.

**Review by BastiaanOlij — APPROVED** [review]
Reviewed during GDExtension meeting, this is looking really good!

**Pull request merged**
