### PR TITLE
Replace legacy hooks with `pre-commit` Python tool

### PR DESCRIPTION
**Pull request by Repiteo**
Overhauls the hook system to utilize the main repo's `pre-commit` hook logic. Migrated relevant files and settings over as needed, as well as applying any detected changes. In particular, this changes the python formatting system from `black` to `ruff` & ensures all the tools used in the checks are now easily accessible via `pyproject.toml`. The `misc/hooks` folder was removed entirely, with all relevant logic being handled in `misc/scripts` or `.pre-commit-config.yaml`.

### CODE REVIEW

**Comment by dsnopek** [comment]
Thanks, this looks really great!

Seems to work perfectly in my testing. Skimming the changes, they seem to match all the equivalents in the Godot repo. And all the code style fixes seem good to me too.

**Review by dsnopek — APPROVED** [review]

**Comment by dsnopek** [comment]
Cherry-picked for 4.2 in PR https://github.com/godotengine/godot-cpp/pull/1527

**Comment by dsnopek** [comment]
Cherry-picked for 4.1 in PR https://github.com/godotengine/godot-cpp/pull/1529

**Comment by bgie** [comment]
The main README.md does not appear to have been updated yet.

It still mentions: 
```Please install clang-format and copy the files in misc/hooks into .git/hooks so formatting is done before your changes are submitted.```

There is a short section about the new `pre-commit` in the main [godot engine documentation](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#pre-commit-hook)

I suppose linking to this would be an acceptable solution?

**Comment by dsnopek** [comment]
> There is a short section about the new `pre-commit` in the main [godot engine documentation](https://docs.godotengine.org/en/latest/contributing/development/code_style_guidelines.html#pre-commit-hook)
> 
> I suppose linking to this would be an acceptable solution?

Yes, I think that would be fine!

Feel free to make a PR to update the README :-)

**Pull request merged**
