### PR TITLE
Add remaining component-wise `min/max` functions to `Vector*`

### PR DESCRIPTION
**Pull request by AThousandShips**
* See: https://github.com/godotengine/godot/pull/80223

### CODE REVIEW

**Review by dsnopek — APPROVED** [review]
This looks good to me! The implementations match their Godot counterparts.

Since this doesn't rely on the Godot PR, I think it'd be fine to merge this even before that PR is merged.

**Review by m4rr5 — APPROVED** [review]
These new functions look good to me.

**Review by bruvzg — APPROVED** [review]
https://github.com/godotengine/godot/pull/73265 probably should be ported as well.

Or maybe we can mod the engine files (math types and templates) to be buildable in both `godot-cpp` and the engine (similar to the `TextServer`s) and sync them by just copying files as is.

**Comment by dsnopek** [comment]
Thanks!

> [godotengine/godot#73265](https://github.com/godotengine/godot/pull/73265) probably should be ported as well.
> 
> Or maybe we can mod the engine files (math types and templates) to be buildable in both `godot-cpp` and the engine (similar to the `TextServer`s) and sync them by just copying files as is.

I think we can address/explore those in follow-up PRs

**Comment by AThousandShips** [comment]
Thank you!

**Pull request merged**
