### PR TITLE
Allow unicode class names

### PR DESCRIPTION
**Pull request by dsnopek**
Depends on PR https://github.com/godotengine/godot/pull/96501

### CODE REVIEW

**Comment by dsnopek** [comment]
This will fail tests until the upstream Godot PR is merged

**Comment by dsnopek** [comment]
Hrm. Compiling locally, the tests work fine. However, on GitHub Actions, both GCC and MSVC don't like the UTC-8 identifiers in the C++ code. I tried setting the `LANG` and `LC_ALL` environment variables, hoping that would help with the GCC on Linux builds, but it had no effect.

This will need some more research to figure out!

**Comment by dsnopek** [comment]
Thanks! I updated to Ubuntu 22.04, which we're using in the static checks already, and that fixes the Linux/GCC builds.

I'm testing out some flags to fix the MSVC build.

**Comment by dsnopek** [comment]
Huzzah! The MSVC flag I tried is working, so this is now fully passing tests :-)

**Review by Ivorforce — APPROVED** [review]
I don't see anything wrong with this, LGTM

**Review by paddy-exe — APPROVED** [review]
Discussed at the GDExtension meeting. Changes look good.

**Pull request merged**
