### PR TITLE
Allow GDExtensions to register virtual methods and call them on scripts (godot-cpp support)

### PR DESCRIPTION
**Pull request by dsnopek**
This depends on PR https://github.com/godotengine/godot/pull/87758

It adds APIs compatible with Godot's, including the following macros:

- `GDVIRTUAL*()` (like `GDVIRTUAL0R()`, `GDVIRTUAL2C()`, etc)
- `GDVIRTUAL_BIND()`
- `GDVIRTUAL_CALL()`
- `GDVIRTUAL_IS_OVERRIDDEN()`
- ... and all the rest!

It also adds an automated test for this functionality to CI.

_NOTE: The tests here will fail until after the Godot PR is merged! However, they are passing for me locally._

Fixes https://github.com/godotengine/godot-cpp/issues/1199
Fixes https://github.com/godotengine/godot-cpp/issues/1072
Fixes https://github.com/godotengine/godot-cpp/issues/910

### CODE REVIEW

**Comment by Remi123** [comment]
I've been waiting for this feature for over a year. Thank you so much.

Glad to see an example. 4.3 will be great for plugin.

**Review by akien-mga — APPROVED** [review]
Didn't review in depth, but looks good at a glance. We merged the upstream counterpart so this could be merged now.

**Comment by Kehom** [comment]
I finally got back to the code I needed this feature. I have noticed that the macros defined in the *gdvirtual.gen.inc* file begin with `StringName _gdvritual_` without explicit namespace usage. This somewhat forces extension code to add `using namespace godot`.

Is this intended?

**Comment by dsnopek** [comment]
> Is this intended?

Nope! This is probably just an artifact of those macros starting out as a copy of the same macros from Godot.

**Comment by dsnopek** [comment]
@Kehom Can you test if this PR fixes it for you? https://github.com/godotengine/godot-cpp/pull/1412 Unfortunately, I don't have a project that doesn't use `using namespace godot` at hand to test if those changes are sufficient

**Comment by Kehom** [comment]
Thanks for the answer. I think it will be best for me to answer about the fix in the PR itself.

**Pull request merged**
