### PR TITLE
added inverse trigonometric functions in Math.hpp

### PR DESCRIPTION
**Pull request by DhruvMaroo**
Added asin, asinf, acos, acosf, atan, atanf in Math.hpp. Related issue: #556.

### CODE REVIEW

**Comment by DhruvMaroo** [comment]
Sorry for the superfluous reverts, they were just because of a mis-click.

**Comment by Zylann** [comment]
Looks good, but you need to fix formatting

**Comment by DhruvMaroo** [comment]
@Zylann Fixed it. I was using spaces instead of tabs.

**Comment by DhruvMaroo** [comment]
@Zylann Could you please merge this? Thank you.

**Comment by Zylann** [comment]
Thanks!

**Pull request merged**
