### PR TITLE
Test built GDNative plugin with stable Godot

### PR DESCRIPTION
**Pull request by o01eg**
Follows up #476 

Runs test a-like script which loads GDNative plugin and checks its methods and properties.

### CODE REVIEW

**Comment by Zylann** [comment]
We switched to Github-Actions fro CI and dev builds, this should be updated to use it instead

**Comment by o01eg** [comment]
Rebased and updated to Github Actions

**Comment by vnen** [comment]
Does this supersede #476? It seems to do the same thing plus an extra step to run a test script, or am I missing something?

**Comment by o01eg** [comment]
Yes, it does the same thing also load built on previous step library and run Godot script to test it.

**Comment by vnen** [comment]
Alright. Then I'll merge this one and close the other.

I still think the test script can be improved to make it easier to extend with other tests and figure out what went wrong, but this can be done in incremental steps later.

**Comment by vnen** [comment]
Thanks!

**Pull request merged**
